
from meta import *

DATA={
        'happy'         : C_C,
        'good'          : C_E,
        'bliss'         : C_B,
        'blissful'      : C_A,
        'cheer'         : C_D,
        'cheery'        : C_C,
        'cheerful'      : C_B,
        'content'       : C_D,
        'contented'     : C_C,
        'merry'         : C_B,
        'joy'           : C_B,
        'joyous'        : C_B,
        'joyful'        : C_B,
        'jovial'        : C_B,
        'jolly'         : C_B,
        'joking'        : C_C,
        'jocular'       : C_B,
        'glee'          : C_B,
        'gleeful'       : C_B,
        'carefree'      : C_B,
        'untroubled'    : C_B,
        'delighted'     : C_B,
        'smiling'       : C_B,
        'beaming'       : C_B,
        'grinning'      : C_B,
        'glowing'       : C_C,
        'satisfied'     : C_C,
        'gratified'     : C_C,
        'sunny'         : C_D,
        'radiant'       : C_D,
        'blithe'        : C_D,
        'blithesome'    : C_D,
        'beatific'      : C_A,
        'cock-a-hoop'   : C_C,
        'thrilled'      : C_C,
        'exuberant'     : C_A,
        'elated'        : C_B,
        'exhilerated'   : C_B,
        'ecstatic'      : C_A,
        'euphoric'      : C_A,
        'overjoyed'     : C_A,
        'exultant'      : C_B,
        'rapt'          : C_B,
        'rapture'       : C_B,
        'rapturous'     : C_B,
        'enraptured'    : C_B,
        'in seventh heaven' : C_B,
        'on cloud nine' : C_B,
        'over the moon' : C_B,
        'walking on air' : C_B,
        'beside myself' : C_B,
        'jumping for joy' : C_B,
        'chirpy'        : C_B,
        'sent'          : C_F,
        'chuffed'       : C_B,
        'as happy as Larry' : C_B,
        'as happy as a clam' : C_B,
        'made up'       : C_F,
        'wrapped'       : C_F,
        'gay'           : C_E,
        'jocose'        : C_B,
        'skippy'        : C_D,
        'fortunate'     : C_B,
        'lucky'         : C_D,
        'favorable'     : C_F,
        'advantageous'  : C_F,
        'opportune'     : C_F,
        'auspicious'    : C_E,
        'apt'           : C_E,
        'beneficial'    : C_D,
        'fitting'       : C_F,
        'befitting'     : C_D,
        'hallelujah'    : C_B,
        'praise'        : C_D,
        'worship'       : C_C,
        'jesus'         : C_D,
        'god'           : C_D,
        'heaven'        : C_C,
    }
