_dict={
        'happy'         : _C,
        'good'          : _E,
        'bliss'         : _B,
        'blissful'      : _A,
        'cheer'         : _D,
        'cheery'        : _C,
        'cheerful'      : _B,
        'content'       : _D,
        'contented'     : _C,
        'merry'         : _B,
        'joy'           : _B,
        'joyous'        : _B,
        'joyful'        : _B,
        'jovial'        : _B,
        'jolly'         : _B,
        'joking'        : _C,
        'jocular'       : _B,
        'glee'          : _B,
        'gleeful'       : _B,
        'carefree'      : _B,
        'untroubled'    : _B,
        'delighted'     : _B,
        'smiling'       : _B,
        'beaming'       : _B,
        'grinning'      : _B,
        'glowing'       : _C,
        'satisfied'     : _C,
        'gratified'     : _C,
        'sunny'         : _D,
        'radiant'       : _D,
        'blithe'        : _D,
        'blithesome'    : _D,
        'beatific'      : _A,
        'cock-a-hoop'   : _C,
        'thrilled'      : _C,
        'exuberant'     : _A,
        'elated'        : _B,
        'exhilerated'   : _B,
        'ecstatic'      : _A,
        'euphoric'      : _A,
        'overjoyed'     : _A,
        'exultant'      : _B,
        'rapt'          : _B,
        'rapture'       : _B,
        'rapturous'     : _B,
        'enraptured'    : _B,
        'in seventh heaven' : _B,
        'on cloud nine' : _B,
        'over the moon' : _B,
        'walking on air' : _B,
        'beside myself' : _B,
        'jumping for joy' : _B,
        'chirpy'        : _B,
        'sent'          : _F,
        'chuffed'       : _B,
        'as happy as Larry' : _B,
        'as happy as a clam' : _B,
        'made up'       : _F,
        'wrapped'       : _F,
        'gay'           : _E,
        'jocose'        : _B,
        'skippy'        : _D,
        'fortunate'     : _B,
        'lucky'         : _D,
        'favorable'     : _F,
        'advantageous'  : _F,
        'opportune'     : _F,
        'auspicious'    : _E,
        'apt'           : _E,
        'beneficial'    : _D,
        'fitting'       : _F,
        'befitting'     : _D,
        'hallelujah'    : _B,
        'praise'        : _D,
        'worship'       : _C,
        'jesus'         : _D,
        'god'           : _D,
        'heaven'        : _C,
    }
