
from meta import *

EMOTES=("^_^",":)","(:","=)","(=","=D","8)","=]","^^","^-^","^__^",
        ":}","{:","=}","{=","[=",)

# (in order from highest to lowest match)
HASHTAGS='''#peaceful #nature #peace #love #photography #sunset #beautiful
#travel #naturephotography #peaceofmind #calm #meditation #life #relax
#happy #photooftheday #instagood #landscape #happiness #winter #art
#mindfulness #sky #beach #travelphotography #yoga #beauty #instagram
#india #bhfyp #ig #relaxing #follow #landscapephotography #positivevibes
#clouds #sea #peaceandlove #trees #mountains #photo #sunrise #wanderlust
#goodvibes #explore #naturelovers #blessed #snow #adventure #family
#grateful #forest #instadaily #world #view #zen #smile #green #serenity
#ocean #peacefull #peacefulplace #peacefulmind #peacefulpakistan
#peacefulness #peacefully #peacefullife #peacefulparenting
#peacefulhooligan #peacefulmorning #peacefulliving #peacefulnight
#peacefulmoment #peacefulplaces #peacefulvibes #peacefulmind
#peacefuleasyfeeling'''


DATA={
    'relaxed'               : C_B,
    'relax'                 : C_C,
    'unwind'                : C_C,
    'loosen up'             : C_C,
    'let up'                : C_C,
    'ease up'               : C_C,
    'ease off'              : C_C,
    'ease'                  : C_D,
    'easy'                  : C_D,
    'slow down'             : C_D,
    'de-stress'             : C_C,
    'unbend'                : C_C,
    'rest'                  : C_C,
    'repose'                : C_C,
    'put my feet up'        : C_C,
    'take it easy'          : C_C,
    'take time off'         : C_C,
    'take some time off'    : C_C,
    'take the day off'      : C_C,
    'take time out'         : C_C,
    'slack off'             : C_D,
    'leisure'               : C_C,
    'laze'                  : C_C,
    'luxuriate'             : C_C,
    'nothing'               : C_C,
    'sit back'              : C_C,
    'lounge'                : C_C,
    'loll'                  : C_C,
    'slump'                 : C_C,
    'flop'                  : C_C,
    'idle'                  : C_C,
    'loaf'                  : C_C,
    'enjoy'                 : C_C,
    'enjoy myself'          : C_C,
    'amuse myself'          : C_C,
    'amuse'                 : C_C,
    'amused'                : C_C,
    'play'                  : C_C,
    'entertain'             : C_C,
    'game'                  : C_C,
    'hang'                  : C_C,
    'hair down'             : C_C,
    'unbutton'              : C_C,
    'veg out'               : C_C,
    'hang loose'            : C_C,
    'stay loose'            : C_C,
    'chill'                 : C_C,
    'chill out'             : C_C,
    'take a chill pill'     : C_C,
    'kick back'             : C_C,
    'calm'                  : C_C,
    'tranquil'              : C_C,
    'tranquilize'           : C_C,
    'calm down'             : C_C,
    'quieten'               : C_C,
    'soothe'                : C_C,
    'pacify'                : C_C,
    'compose'               : C_D,
    'alleviate'             : C_D,
    'slacken'               : C_D,
    'lessen'                : C_D,
    'loosen'                : C_D,
    'mitigate'              : C_E,
    'qualify'               : C_E,
    'moderate'              : C_E,
    'modify'                : C_E,
    'temper'                : C_E,
    'restful'               : C_C,
    'pleasant'              : C_C,
    'quiet'                 : C_C,
    'still'                 : C_C,
    'relaxing'              : C_C,
    'soothing'              : C_C,
    'sleepy'                : C_C,
    'sleep'                 : C_C,
    'silent'                : C_C,
    'soundless'             : C_C,
    'hushed'                : C_C,
    'noiseless'             : C_C,
    'undisturbed'           : C_C,
    'untroubled'            : C_C,
    'private'               : C_C,
    'secluded'              : C_C,
    'solitary'              : C_C,
    'isolated'              : C_C,
    'serene'                : C_C,
    'composed'              : C_C,
    'placid'                : C_C,
    'at peace'              : C_C,
    'peace'                 : C_C,
    'peaceful'              : C_B,
    'at rest'               : C_B,
    'at ease'               : C_B,
    'in repose'             : C_C,
    'reposeful'             : C_C,
    'unworried'             : C_B,
    'unruffled'             : C_B,
    'anxiety-free'          : C_B,
    'content'               : C_B,
    'blissful'              : C_B,
    'secure'                : C_C,
    'sukhdeep'    : C_E,
    'canada'    : C_E,
    'stoner'    : C_E,
    'buddhism'    : C_E,
    'jordan'    : C_E,
    'alone'    : C_E,
    'superlove'    : C_E,
    'flicka'    : C_E,
    'mackensie'    : C_E,
    'solomon'    : C_E,
    'ramneek'    : C_E,
    'saumya'    : C_E,
    'oregon'    : C_E,
    'erin'    : C_E,
    'darcy'    : C_E,
    'purple haze'    : C_D,
    'maliah'    : C_E,
    'federico'    : C_E,
    'orthodox'    : C_E,
    'deanna'    : C_E,
    'frieda'    : C_E,
    'iranium'    : C_E,
    'satyn'    : C_E,
    'joyette'    : C_E,
    'going iranian'    : C_E,
    'yoko ono'    : C_E,
    'cannonize'    : C_E,
    'gunga galunga'    : C_E,
    'thuan'    : C_E,
    'chessa'    : C_E,
    'fredrikke'    : C_E,
    'bluefield'    : C_E,
    'adanna'    : C_E,
    'malakai'    : C_E,
    'canadians'    : C_E,
    'amandeep'    : C_E,
    'costa rica'    : C_E,
    'cymbalize'    : C_E,
    'allihater'    : C_E,
    'gulla gulla island'    : C_E,
    'strill'    : C_E,
    'vietnam'    : C_E,
    'vash the stampede'    : C_E,
    'arihant'    : C_E,
    'colon three'    : C_E,
    'pacific'    : C_E,
    'tiaira'    : C_E,
    "keepin' it buddha"    : C_E,
    'yarrowed'    : C_E,
    'pixy false'    : C_E,
    'dmz'    : C_E,
    'british'    : C_E,
    'lotus eater'    : C_E,
    'maddie mcmahon'    : C_E,
}
