_dict={
        'sad'           : _C,
        'bad'           : _E,
        'downcast'      : _C,
        'downhearted'   : _C,
        'heartbroken'   : _B,
        'brokenhearted' : _B,
        'broken-hearted' : _B,
        'broken heart'  : _B,
        'down'          : _E,
        'disconsolate'  : _B,
        'doleful'       : _B,
        'dismal'        : _B,
        'blue'          : _F,
        'low-spirited'  : _B,
        'mourn'         : _D,
        'mournful'      : _B,
        'woe'           : _B,
        'woeful'        : _B,
        'woe is me'     : _A,
        'woebegone'     : _A,
        'forlorn'       : _B,
        'crestfallen'   : _B,
        'inconsolable'  : _B,
        'grief'         : _D,
        'grief-stricken' : _B,
        'down in the mouth' : _B,
        'down in the dumps' : _B,
        'unhappy'       : _B,
        'sorrow'        : _B,
        'sorrowful'     : _B,
        'dejected'      : _B,
        'rejected'      : _B,
        'regret'        : _C,
        'regretful'     : _B,
        'tragic'        : _C,
        'unfortunate'   : _D,
        'awful'         : _D,
        'miserable'     : _C,
        'pessimistic'   : _D,
        'melancholy'    : _C,
        'melancholic'   : _C,
        'depressed'     : _B,
        'anxious'       : _C,
        'lonely'        : _B,
        'gloomy'        : _B,
        'negative'      : _E,
        'defeat'        : _D,
        'defeatist'     : _C,
        'downbeat'      : _C,
        'cynical'       : _D,
        'bleak'         : _C,
        'despair'       : _B,
        'despairing'    : _B,
        'black'         : _F,
        'despondent'    : _C,
        'demoralized'   : _C,
        'hopeless'      : _B,
        'glum'          : _C,
        'lugubrious'    : _E,
        'suspicious'    : _E,
        'distrustful'   : _E,
        'doubting'      : _E,
        'hell'          : _B,
        'living hell'   : _A,
        'uncomfortable' : _D,
    }
