
from ModelTraining.machinegym.meta import *


EMOTES=('):<','>:(','D:','D:<','d:<','>:e','>:v','v:<','-__-','-_-',
        '-.-','._.',)

HASHTAGS='''#angry 
#mad #angryface 
#angryeyes 
#attitude #anger #angryfeminist 
#jealous #angrymom #angrybaby 
#angryallthetime #angryme #angrymood 
#sketch 
#angrywoman #catsofinstagram #angrycat #angryyoungman
#angryorchard #angrycat #angryface #angrybaby #angrydog #angrykitty
#angryeyes #angrymom #angrysky #angryman #angrygirl #angrybeavers
#angrycats #angrylook'''

DATA={
    'angry'                 : C_C,
    'red'                   : C_E,
    'seeing red'            : C_D,
    'irate'                 : C_B,
    'annoyed'               : C_C,
    'cross'                 : C_C,
    'vexed'                 : C_C,
    'irritated'             : C_C,
    'exasperated'           : C_C,
    'indignant'             : C_C,
    'aggrieved'             : C_C,
    'irked'                 : C_C,
    'piqued'                : C_C,
    'displeased'            : C_C,
    'provoked'              : C_C,
    'galled'                : C_C,
    'resentful'             : C_C,
    'furious'               : C_C,
    'enraged'               : C_C,
    'infuriated'            : C_C,
    'incensed'              : C_C,
    'raging'                : C_C,
    'incandescent'          : C_C,
    'wrathful'              : C_C,
    'fuming'                : C_C,
    'ranting'               : C_C,
    'raving'                : C_C,
    'seething'              : C_C,
    'frenzied'              : C_C,
    'beside myself'         : C_C,
    'outraged'              : C_C,
    'irascible'             : C_C,
    'choleric'              : C_C,
    'splenetic'             : C_C,
    'dyspeptic'             : C_C,
    'tetchy'                : C_C,
    'testy'                 : C_C,
    'crabby'                : C_C,
    'waspish'               : C_C,
    'hostile'               : C_C,
    'antagonistic'          : C_C,
    'black'                 : C_C,
    'dark'                  : C_C,
    'dirty'                 : C_C,
    'filthy'                : C_C,
    'mad'                   : C_C,
    'wild'                  : C_C,
    'livid'                 : C_C,
    'boiling'               : C_C,
    'apoplectic'            : C_C,
    'aerated'               : C_C,
    'riled'                 : C_C,
    'aggravated'            : C_C,
    'snappy'                : C_C,
    'snappish'              : C_C,
    'shirty'                : C_C,
    'stroppy'               : C_C,
    'narky'                 : C_C,
    'ratty'                 : C_C,
    'sore'                  : C_C,
    'eggy'                  : C_C,
    'bent out of shape'     : C_C,
    'soreheaded'            : C_C,
    'teed off'              : C_C,
    'ticked off'            : C_C,
    'ropeable'              : C_C,
    'snaky'                 : C_C,
    'crook'                 : C_C,
    'vex'                   : C_C,
    'in a bate'             : C_C,
    'waxy'                  : C_C,
    'ireful'                : C_C,
    'wroth'                 : C_C,
    'heated'                : C_C,
    'hot'                   : C_C,
    'passionate'            : C_C,
    'fiery'                 : C_C,
    'stormy'                : C_C,
    'tempestuous'           : C_C,
    'lively'                : C_C,
    'ill-tempered'          : C_C,
    'acrimonious'           : C_C,
    'bitter'                : C_C,
    'pissed'                : C_C,
    'pissed off'            : C_C,
    'piss me off'           : C_C,
    'pissed me off'         : C_C,
    'pisses me off'         : C_C,
    'fit to be tied'        : C_C,
    'in a paddy'            : C_C,
    'in a lather'           : C_C,
    'riled up'              : C_C,
    'steamed up'            : C_C,
    'foaming at the mouth'  : C_C,
    'with all guns blazing' : C_C,
    'with guns blazing'     : C_C,
    'up in arms'            : C_C,
    'on the warpath'        : C_C,
    'hot under the collar'  : C_C,
    'hopping mad'           : C_C,
    'in a frenzy'           : C_C,
    'in high dungeon'       : C_C,
    'in a temper'           : C_C,
    'as cross as two sticks': C_C,
    'chapped'               : C_C,
    'salty'                 : C_C,
    'rabiosa'               : C_C,
    'hangry'                : C_C,
    'lewis black'           : C_C,
    'fuu'                   : C_C,
    'fuuu'                  : C_C,
    'fuuuu'                 : C_C,
    'whisked'               : C_C,
    'grr'                   : C_C,
    'grr'                   : C_C,
    'lane'                  : C_C,
    'drove'                 : C_C,
    'bleak'                 : C_C,
    'frothy'                : C_C,
    'ripshit'               : C_C,
    'cheesed off'           : C_C,
    'agro'                  : C_C,
    'aggro'                 : C_C,
    'ripping'               : C_C,
    'far'                   : C_C,
    'hacked off'            : C_C,
    'ape shit'              : C_C,
    'tight'                 : C_C,
    'angrate'               : C_C,
    'headbutt'              : C_C,
    'cheesed'               : C_C,
    'honked off'            : C_C,
    'aggy'                  : C_C,
    'jangry'                : C_C,
    'cantankerous'          : C_C,
    'torqued'               : C_C,
    'gargled'               : C_C,
    'chizzy'                : C_C,
    'u mad'                 : C_C,
    'fit to be tied'        : C_C,
    'mingey'                : C_C,
    'mangry'                : C_C,
    'hexstatik'             : C_C,
    'damn'                  : C_C,
    'abs'                   : C_C,
    'mad tight'             : C_C,
    'guh'                   : C_C,
    'rattled'               : C_C,
    'mad-fat'               : C_C,
    'dag gummit'            : C_C,
    'mudachuka'             : C_C,
    'nimph'                 : C_C,
    'snakey'                : C_C,
    'agitated'              : C_C,
    'angrify'               : C_C,
    'angus'                 : C_C,
    'sour'                  : C_C,
    'resent'                : C_C,
    'eat shit and die'      : C_C,
    'gargled'               : C_C,
}
