
from ModelTraining.machinegym.meta import *

# taken 4/22/2020; note the prevalence of covid / coronavirus in hashtags


EMOTES=('O.O','o.o','O_O','o_o',':(','):','=(',')=',':[',']:','=[',']=',
        'D:',)

HASHTAGS='''#fear #anxiety #covid #horror #coronavirus
#scary
#dark #creepy #corona #stress
#terror #halloween 
#pandemic #death
#panic #miedo #darkness
#scared 
#ghost #fearofgod #fears #fearthewalkingdead
#fearofheights'''

DATA={
    'fear'     : C_C,
    'fright'     : C_C,
    'fearful'     : C_C,
    'fearsome'     : C_C,
    'fearfulness'     : C_C,
    'afraid'     : C_C,
    'terror'     : C_C,
    'terrified'     : C_C,
    'horror'     : C_C,
    'horrified'     : C_C,
    'alarm'     : C_C,
    'panic'     : C_C,
    'agitation'     : C_C,
    'trepidation'     : C_C,
    'dread'     : C_C,
    'consternation'     : C_C,
    'dismay'     : C_C,
    'distress'     : C_C,
    'anxiety'     : C_C,
    'worry'     : C_C,
    'angst'     : C_C,
    'unease'     : C_C,
    'uneasiness'     : C_C,
    'apprehension'     : C_C,
    'apprehensiveness'     : C_C,
    'apprehensive'     : C_C,
    'nervous'     : C_C,
    'nervousness'     : C_C,
    'nerves'     : C_C,
    'timid'     : C_C,
    'timidity'     : C_C,
    'disquiet'     : C_C,
    'disquietude'     : C_C,
    'discomposure'     : C_C,
    'unrest'     : C_C,
    'perturbation'     : C_C,
    'foreboding'     : C_C,
    'the shakes'     : C_C,
    'collywobbles'     : C_C,
    'jitterness'     : C_C,
    'twitchiness'     : C_C,
    'willies'     : C_C,
    'the willies'     : C_B,
    'creeps'     : C_D,
    'the creeps'     : C_C,
    'funk'     : C_C,
    'blue funk'     : C_C,
    'worriment'     : C_C,
    'inquietude'     : C_C,
    'phobia'     : C_C,
    'aversion'     : C_C,
    'antipahty'     : C_C,
    'bugbear'     : C_C,
    'bogey'     : C_C,
    'nightmare'     : C_C,
    'neuosis'     : C_C,
    'complex'     : C_C,
    'mania'     : C_C,
    'abnormal fear'     : C_A,
    'irrational fear'     : C_B,
    'obsessive fear'     : C_S,
    'hang-up'     : C_E,
    'frightened'     : C_C,
    'scared'     : C_C,
    'scared stiff'     : C_C,
    'terror stricken'     : C_C, # dashes?
    'terror struck'     : C_C,
    'horror stricken'     : C_C,
    'horror struck'     : C_C,
    'petrified'     : C_C,
    'scared to death'     : C_C,
    'intimidated'     : C_C,
    'intimidate'     : C_C,
    'alarmed'     : C_C,
    'uneasy'     : C_C,
    'tense'     : C_C,
    'worried'     : C_C,
    'panicky'     : C_C,
    'beside myself'     : C_C,
    'scared witless'     : C_C,
    'frantic'     : C_C,
    'hysterical'     : C_E,
    'shaking in my shoes'     : C_C,
    'shaking like a leaf'     : C_C,
    'timid'     : C_C,
    'timorous'     : C_C,
    'faint hearted'     : C_C,
    'cowardly'     : C_C,
    'coward'     : C_C,
    'cowed'     : C_D,
    'pusillanimous'     : C_C,
    'daunted'     : C_C,
    'nervy'     : C_C,
    'cold sweat'     : C_E,
    'blue funk'     : C_E,
    'in a flap'     : C_E,
    'in a fluster'     : C_E,
    'in a state'     : C_E,
    'in a tizzy'     : C_E,
    'in a jizz'     : C_E,
    'yellow'     : C_E,
    'chicken'     : C_E,
    'jittery'     : C_D,
    'jumpy'     : C_C,
    'frit'     : C_C,
    'feart'     : C_C,
    'spooked'     : C_D,
    'afeared'     : C_C,
    'affrighted'     : C_C,
    'shit scared'     : C_A,
    'expose'     : C_D,
    'exposed'     : C_D,
    'exposing'     : C_E,
    'exposure'     : C_E,
    'neglect'     : C_D,
    'neglected'     : C_D,
    'neglecting'     : C_D,
    'attack'     : C_D,
    'attacked'     : C_D,
    'attacking'     : C_D,
    'harm'     : C_D,
    'pain'     : C_C,
    'damage'     : C_D,
    'critical'     : C_E,
    'peril'     : C_A,
    'danger'     : C_B,
    'warning'     : C_C,
    'attention'     : C_E,
}
