
from meta import *

# "having fun," not "making fun."


EMOTES=(":d",":D","^_^",": d",">3",":)","(:","=)","(=","=D","8)","=]",
        "8d","8D","8P",":P",":p","=P","=p","^^","8^d",":')","=')",)

HASHTAGS='''#fun #love #instagood #happy #like #follow #friends #smile
#photooftheday #funny #cute #beautiful #me #life #followme #instadaily
#picoftheday #instagram #art #fashion #photography #style #music #family
#party #memes #travel #selfie #nature #bhfyp #girl #summer #dance #meme
#food #fitness #instalike #igers #lol #funnymemes #kids #tbt #amazing
#photo #comedy #instamood #myself #cool #likeforlikes #bhfyp #beauty
#lifestyle #repost #sun #sport #adventure #f #happiness #holiday
#motivation #funny #funnymemes #funnytimes #funnyvideos #funday
#funnyshit #funnymeme #funk #funtime #funkopop #funko #funnypictures
#funinthesun #funtionaltraining #funnight #funcional #funky #fundraiser
#funnyposts #funnyvideo #funraiser'''

DATA={
    'fun'                   : C_C,
    'energized'             : C_C,
    'enthusiastic'          : C_C,
    'exhilerate'            : C_C,
    'exhilerated'           : C_C,
    'refreshed'             : C_D,
    'interest'              : C_B,
    'interested'            : C_C,
    'interesting'           : C_B,
    'excite'                : C_B,
    'excited'               : C_B,
    'exciting'              : C_B,
    'excitment'             : C_B,
    'amuse'                 : C_C,
    'amused'                : C_B,
    'amusing'               : C_B,
    'amusement'             : C_C,
    'entertain'             : C_C,
    'entertained'           : C_B,
    'entertaining'          : C_B,
    'entertainment'         : C_C,
    'enjoy'                 : C_C,
    'enjoying'              : C_B,
    'enjoyable'             : C_B,
    'enjoyment'             : C_D,
    'lively'                : C_D,
    'boisterous'            : C_E,
    'convivial'             : C_C,
    'diverting'             : C_C,
    'merry'                 : C_C,
    'merrymaking'           : C_D,
    'witty'                 : C_E,
    'pleasant'              : C_D,
    'pleasure'              : C_C,
    'pleasureable'          : C_C,
    'pleasurable'           : C_C,
    'pleasing'              : C_D,
    'pleases'               : C_E,
    'gratify'               : C_E,
    'gratification'         : C_D,
    'jollification'         : C_C,
    'leisure'               : C_C,
    'relaxation'            : C_C,
    'relief'                : C_C,
    'respite'               : C_C,
    'rest'                  : C_C,
    'refreshment'           : C_C,
    'recreation'            : C_C,
    'diversion'             : C_C,
    'distraction'           : C_C,
    'good time'             : C_C,
    'great time'            : C_C,
    'r and r'               : C_C,
    'living it up'          : C_C,
    'live it up'            : C_C,
    'junketing'             : C_C,
    'a ball'                : C_D,
    'having a ball'         : C_B,
    'whoopee'               : C_C,
    'yay'                   : C_C,
    'laughter'              : C_C,
    'hilarity'              : C_C,
    'beer and skittles'     : C_C,
    'cheer'                 : C_C,
    'cheery'                : C_C,
    'cheering'              : C_C,
    'cheerfulness'          : C_C,
    'cheeriness'            : C_C,
    'joy'                   : C_C,
    'joyous'                : C_C,
    'joysome'               : C_C,
    'jollity'               : C_C,
    'joviality'             : C_C,
    'jocularity'            : C_C,
    'high spirits'          : C_C,
    'high spirited'         : C_C,
    'gaiety'                : C_C,
    'gay'                   : C_C,
    'mirth'                 : C_C,
    'mirthfulness'          : C_C,
    'glee'                  : C_C,
    'gladness'              : C_C,
    'glad'                  : C_C,
    'light-hearted'         : C_C,
    'light-heartedness'     : C_C,
    'levity'                : C_C,
    'vivacity'              : C_C,
    'liveliness'            : C_C,
    'exuberance'            : C_C,
    'exuberant'             : C_C,
    'ebullience'            : C_C,
    'buoyancy'              : C_E,
    'perkiness'             : C_D,
    'zest'                  : C_D,
    'sunniness'             : C_D,
    'brightness'            : C_E,
    'enthusiasm'            : C_C,
    'vibrancy'              : C_C,
    'vibrant'               : C_C,
    'vividness'             : C_D,
    'vivid'                 : C_E,
    'vitality'              : C_D,
    'energy'                : C_D,
    'vigor'                 : C_D,
    'vim'                   : C_E,
    'sport'                 : C_C,
    'fun'                   : C_C,
}
