# Generated by Django 3.0.2 on 2020-02-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('Email', models.CharField(default='placeholder@emai.xyz', max_length=50, primary_key=True, serialize=False)),
                ('EmailSent', models.BooleanField(default=False)),
            ],
        ),
    ]
