# Generated by Django 3.0.2 on 2020-02-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
