# Generated by Django 3.0.3 on 2020-04-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200226_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=768)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='email',
            name='tweet_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp.Tweets')),
                ('text', models.CharField(max_length=256)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
